spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.85.166:3306/guli_oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  application:
    name: gulimall-oms
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:9949
      config:
        server-addr: 127.0.0.1:9949

mybatis-plus:
  mapper-locations: classpath:/mapper/pms/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 10002